secretGenerator:
  - name: mysql-pass
    literals:
      - password=test
resources:
  - mysql-deployment.yaml
  - mysql-service.yaml
#  - mysql-persistentvolumeclaim.yaml
#  - wordpress-deployment.yaml
#  - wordpress-service.yaml
#  - wordpress-persistentvolumeclaim.yaml
