apiVersion: v1 # apply時に使用するAPIの種別。kindによって決まる
kind: Service # Serviceリソースのマニフェスト
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
